<!DOCTYPE html>
<html>
<head>
  <title>Reservation Page</title>
  <script src="https://cdn.emailjs.com/dist/email.min.js"></script>
  <script>
    (function(){
      emailjs.init("lcWxOinJBUuyL-C0M");
    })();
  </script>
</head>
<body>


<body>

  <h1>Make a Reservation</h1>   

  <form>
    <label for="name">Name:</label><br>
    <input type="text" id="name"><br><br>

    <label for="email">Email:</label><br>
    <input type="email" id="email"><br><br>

    <label for="guests">Number of Guests:</label><br>
    <input type="number" id="guests" min="1"><br><br>

    <label for="date">Date:</label><br>
    <input type="date" id="date"><br><br>

    <label for="time">Time:</label><br>
    <input type="time" id="time"><br><br>

    <button type="submit" onclick="sendMail">Submit</button>
  </form>

  <script>
    document.getElementById('reservation-form').addEventListener('submit', function(event) {
      event.preventDefault();

      emailjs.sendForm('service_21cqpgr', 'template_rxj4nsl', this)
        .then(function() {
          alert('Reservation Sent!');
        }, function(error) {
          alert('FAILED...', error);
        });
    });
  </script>

</body>
</html>
